
CREATE TABLE "TB_PVSM_NECONN_MST" 	
   (	
	"NEAGENT_ID" varchar(10) , 
	"NEA_APPNAME" varchar(10), 
	"NEA_PODNAME" varchar(20), 
	"CONN_IP_A" varchar(15) , 
	"CONN_IP_B" varchar(15) , 
	"CONN_IP_D" varchar(15) , 
	"FAILOVER_POLICY" varchar(10) , 
	"FAILOVER_RETRY_COUNT" BIGINT, 
	"RECONNECTION_TRY_INTERVAL_SEC" BIGINT, 
	"BORROW_WAIT_TIMEOUT" BIGINT, 
	"BORROW_WAIT_TIMEOUT_RETRY_COUNT" BIGINT, 
	"READ_TIMEOUT" BIGINT, 
	"READ_TIMEOUT_RETRY_COUNT" BIGINT, 
	"WRITE_TIMEOUT" BIGINT, 
	"WRITE_TIMEOUT_RETRY_COUNT" BIGINT, 
	"BACKUP_TYPE" varchar(20) , 
	"DR_EXIST_YN" CHAR(1) , 
	"AUTO_FAILOVER_YN" CHAR(1) , 
	"HEARTBEAT_YN" CHAR(1) , 
	"HEARTBEAT_INTERVAL" BIGINT, 
	"HEARTBEAT_TRY_COUNT" BIGINT, 
	"HEARTBEAT_MESSAGE" varchar(255) , 
	"NE_MANAGEMENT" varchar(255) , 
	"DESCRIPTION" varchar(1000) , 
	"CONN_MODE" VARCHAR(10)
   );

  INSERT INTO "TB_PVSM_NECONN_MST" ("NEAGENT_ID","NEA_APPNAME","NEA_PODNAME","CONN_IP_A","CONN_IP_B","CONN_IP_D","FAILOVER_POLICY","FAILOVER_RETRY_COUNT","RECONNECTION_TRY_INTERVAL_SEC",
  "BORROW_WAIT_TIMEOUT","BORROW_WAIT_TIMEOUT_RETRY_COUNT","READ_TIMEOUT","READ_TIMEOUT_RETRY_COUNT","WRITE_TIMEOUT","WRITE_TIMEOUT_RETRY_COUNT","BACKUP_TYPE","DR_EXIST_YN","AUTO_FAILOVER_YN","HEARTBEAT_YN",
  "HEARTBEAT_INTERVAL","HEARTBEAT_TRY_COUNT","HEARTBEAT_MESSAGE","NE_MANAGEMENT","DESCRIPTION","CONN_MODE") VALUES
	 ('CNAP1','CNAP','nea-cnap-0','127.0.0.1','127.0.0.1','127.0.0.1',NULL,NULL,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'BW'),
	 ('CNAP2','CNAP','nea-cnap-1','127.0.0.1','127.0.0.1','127.0.0.1',NULL,NULL,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'BW'),
	 ('HSS1','HSS','nea-4ghss-0','127.0.0.1','127.0.0.1','127.0.0.1','Port',12,5,10,3,60,3,30,5,'Cold','Y','Y','Y',30,5,'check heartbeat message [1]','01099928380','4GHSS','SOCKET');

	
  
  
CREATE TABLE "TB_PVSM_NECONN_DTL" 	
   (	
    "NECONN_ID" BIGINT, 
	"NEA_PODNAME" varchar(20), 
	"NEA_PROCNAME" varchar(255), 
	"NEAGENT_ID" varchar(10) , 
	"CONN_COUNT" BIGINT, 
	"CONN_KEY" varchar(1) , 
	"CONN_PORT_A" BIGINT, 
	"CONN_PORT_B" BIGINT, 
	"CONN_PORT_D" BIGINT, 
	"CONN_TYPE" varchar(10) , 
	"CONN_GROUPNAME" varchar(10) , 
	"CONN_STATE" CHAR(1) , 
	"CONN_IP_TYPE" CHAR(1) , 
	"CONN_REAL_COUNT" BIGINT ,
	"UPDATE_TIME" TIMESTAMP
   );

INSERT INTO "TB_PVSM_NECONN_DTL" ("NECONN_ID","NEA_PODNAME","NEA_PROCNAME","NEAGENT_ID","CONN_COUNT","CONN_KEY","CONN_PORT_A","CONN_PORT_B","CONN_PORT_D","CONN_TYPE","CONN_GROUPNAME","CONN_STATE","CONN_IP_TYPE","CONN_REAL_COUNT","UPDATE_TIME") VALUES
 (6,'nea-cnap-0','AgentCNAP','CNAP1',1,'A',7002,NULL,NULL,'POOL','CNAP-G1','0','A',0,NULL),
 (7,'nea-cnap-1','AgentCNAP','CNAP2',1,'A',7001,NULL,NULL,'POOL','CNAP-G1','0','A',0,NULL),
 (1,'nea-4ghss-0','AgentHSS','HSS1',1,'A',9101,19101,29101,'POOL','HSS-G1','1','A',1,NULL),
 (2,'nea-4ghss-0','AgentHSS','HSS2',1,'B',9102,19102,29102,'POOL','HSS-G1','0','A',0,NULL),
 (3,'nea-4ghss-0','AgentHSS','HSS3',1,'C',9103,19103,29103,'POOL','HSS-G1','1','A',1,NULL),
 (4,'nea-4ghss-0','AgentVMS','HSS4',1,'D',9104,19104,29104,'POOL','VMS-G1','1','A',1,NULL);

select B."NECONN_ID", A."NEA_APPNAME", A."NEA_PODNAME", B."NEA_PROCNAME", B."CONN_COUNT", 
	B."CONN_KEY", A."CONN_IP_A", B."CONN_PORT_A", A."CONN_IP_B", B."CONN_PORT_B", A."CONN_IP_D", 
	B."CONN_PORT_D", B."CONN_TYPE", B."CONN_GROUPNAME", A."FAILOVER_POLICY", A."FAILOVER_RETRY_COUNT", 
	A."RECONNECTION_TRY_INTERVAL_SEC", A."BORROW_WAIT_TIMEOUT", A."BORROW_WAIT_TIMEOUT_RETRY_COUNT", A."READ_TIMEOUT", 
	A."READ_TIMEOUT_RETRY_COUNT", A."WRITE_TIMEOUT", A."WRITE_TIMEOUT_RETRY_COUNT", A."BACKUP_TYPE", A."DR_EXIST_YN", 
	A."AUTO_FAILOVER_YN", A."HEARTBEAT_YN", A."HEARTBEAT_INTERVAL", A."HEARTBEAT_TRY_COUNT", A."HEARTBEAT_MESSAGE", 
	A."NE_MANAGEMENT", A."DESCRIPTION", A."CONN_MODE" 
from "TB_PVSM_NECONN_MST" A inner join "TB_PVSM_NECONN_DTL" B on A."NEA_PODNAME" = 'nea-4ghss-0' and A."NEA_PODNAME" = B."NEA_PODNAME";

select * from "TB_PVSM_NECONN_DTL";

update "TB_PVSM_NECONN_DTL" set "CONN_STATE"='0', "CONN_IP_TYPE"='A', "CONN_REAL_COUNT"=0, "UPDATE_TIME"=current_timestamp  where "NEA_PODNAME"='nea-4ghss-0'; 

select * from "TB_PVSM_NECONN_DTL" tpnd ;
update "TB_PVSM_NECONN_DTL" set "CONN_STATE"='0', "CONN_IP_TYPE"='A', "CONN_REAL_COUNT"=1, "UPDATE_TIME"=current_timestamp  where "NECONN_ID"=4; 
